spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:derby:derbydb;create=true
  application:
    name: new-app
    
server:
  port: 8070
  servlet:
    context-path: /gsp
logging:
  file: app.log
